### ISSUE TITLE
upgrade software to newer versions

### ISSUE THREAD

**Issue by dprelipcean** [reanahub/reana-env-root6#4]
`Python2` will end its lifetime soon and we should transition to `python3`. This is also prompted by the docker image that inherits from this one in the [BSM search example](https://github.com/reanahub/reana-demo-bsm-search). This includes:

- OS system (ubuntu:trusty is 14.04, could upgrade to 18.x)
- Python3 (may inherit from above)
- ROOT: newest version is v6-18-04, compared to root-v6-02-12

See also #1 for discussion.

**Comment by dprelipcean** [comment]
I have tried to to the plain changes, but they also require small dependencies changes. Since we use this image for multiple examples as it is, maybe it would be a good idea to keep this one, and have another one with newer software?

**Comment by tiborsimko** [comment]
We can definitely have more `reana-env-root6` images with different tags, say `1.0` for current Python2-based image and `2.0` for Python3-based image.

**Comment by tiborsimko** [comment]
... that said, since we are in the pilot phase, we can simply update the latest image for now.  Depending on whether the demo examples are working?  Here's the list to check that use `reana-env-root6`:

- reana-demo-bsm-search
- reana-demo-lhcb-d2pimumu
- reana-demo-root6-roofit


If these are OK with the new Python3-based image, we can simply replace the current Dockerfile.  (And if we need to get back to Python2 one day, we can tag an older release using Git history; no problem.)

**Comment by dprelipcean** [comment]
I have finally built the image, but it took ages. It is available [here](https://cloud.docker.com/u/dprelipcean/repository/docker/dprelipcean/reana-env-root6).
